### ISSUE TITLE
Please consider making this repo private

### ISSUE THREAD

**Issue by getify** [kutyel/functional-light#3]
I appreciate that you've taken the course and enjoyed the exercises.

However, by publishing them up here, you're making that content available for anyone to get. Normally, I reserve the materials from my courses from being published publicly, so as to protect the financial viability of the course from being watered down.

Of course, I can't force you to do so, but please consider making this repo private. Or at a minimum, I'd appreciate a note being added to the repo/readme that indicates that the materials here are not openly licensed, as is usually implied/assumed with public repositories.

Thanks for your consideration. :)

**Comment by kutyel** [comment]
Unfortunately, I don't have a paid subscription to GitHub, so I can't make it private. I can delete the original files with the exercises with the readme's, leaving only my solutions (which are very different to the originals) or change the license of the whole repo to be something more restrictive (instead of MIT). What do you prefer? Sorry for the inconvenience 😕

**Comment by getify** [comment]
Leaving only your solution files is probably the best option. Thanks for understanding. :)

**Comment by kutyel** [comment]
No problem! Will do it first thing in the morning tomorrow 😉
